#!/bin/bash
# Check Pharo MCP connection on session start

PHARO_PORT="${PHARO_SIS_PORT:-8086}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 Smalltalk Development Environment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 MCP Servers:"
echo "   • pharo-interop: Pharo Smalltalk Interop"
echo "   • smalltalk-validator: Tonel Validator"
echo ""
echo "🌐 Pharo Connection:"
echo "   Expected port: $PHARO_PORT"
echo "   Make sure PharoSmalltalkInteropServer is running"
echo ""
echo "💡 Quick Start:"
echo "   1. Edit .st files in your project"
echo "   2. Run: /st:import PackageName /absolute/path/to/src"
echo "   3. Run: /st:test TestClassName"
echo ""
echo "📚 Available commands:"
echo "   /st:import  - Import Tonel package to Pharo"
echo "   /st:test    - Run SUnit tests"
echo "   /st:validate - Validate Tonel syntax"
echo ""
echo "🎯 Skills:"
echo "   • smalltalk-developer - Development workflow"
echo "   • smalltalk-debugger  - Debugging techniques"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
